name: Terraform Apply and Destroy
on:
  workflow_dispatch: 
   inputs:
      var1:
        
          
  push:
    branches:
      - main
     
jobs:
  terraform_apply_destroy:
    name: Terraform Apply & Destroy
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ap-south-1
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}"

      - name: Terraform Apply
        if: github.event.inputs.var1 == 'apply'
        run: terraform apply -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}" -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.var1 == 'destroy'
        run: terraform destroy -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}" -auto-approve
