name: Terraform ${{ github.event.inputs.action }}
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action to perform'
        required: true
        type: choice
        options:
          - apply
          - destroy
  # push:
  #   branches:
  #     - main
     
jobs:
  terraform_apply_destroy:
    name: terraform ${{ github.event.inputs.action }}
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      AWS_DEFAULT_REGION: ap-south-1
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="bucket=${{secrets.BUCKET }}" -backend-config="key=${{secrets.TFSTATE_FILE }}" -backend-config="region=${{secrets.AWS_REGION }}" 
      
      - name: Terraform Plan
        run: terraform plan -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}"

      - name: Terraform Apply or Destroy
        # if: github.event_name == 'workflow_dispatch'
        run: terraform ${{ github.event.inputs.action }} -var="NEWRELIC_ACCOUNT_ID=${{ secrets.NEWRELIC_ACCOUNT_ID }}" -var="NEWRELIC_API_KEY=${{ secrets.NEWRELIC_API_KEY }}" -auto-approve
